Hee playing in class  musi
taking
destruction not playing\ attendtion

Mad and throw his shoe

During music class,
Garen was taking
Garen not paying attention
Garen was descrutive to ther student during learning
when he was talked to, he got mad and threw his shoes

itvv kglv kong pymf

kubectl create secret generic gmail-smtp-secret \
  -n monitoring \
  --from-literal=password='itvvkglvkongpymf'
