apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ai-platform-gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/jcloudcodesgroup/ai-platform-gitops.git
  username: oauth2
  password: glpat-AX5RogqdL5rX-7nG4ae_lmM6MQpvOjEKdTpseXZidQ8.01.170vaoq63
